::[Bat To Exe Converter]
::
::fBE1pAF6MU+EWHreyHcjLQlHcCeQNXiuD7QS1Mz+/OGTrV0heMcTVKCV/4yrHMMc7kzncNYe2WhdncUYCSd0Wz6HQTMYjEJumSqPJ8D8
::fBE1pAF6MU+EWHreyHcjLQlHcCeQNXiuD7QS1Mz+/OGTrV0heMcTVKCV/4yrHMMc7kzncNYe2WhdncUYCSd0Wz6HQTMYjEJumSqJOcz8
::fBE1pAF6MU+EWHreyHcjLQlHcCeQNXiuD7QS1Mz+/OGTrV0heMcTVKCV/4yrHMMc7kzncNYe2WhdncUYCSd0Wz6HQTM5umlAuXzLIcWP0w==
::fBE1pAF6MU+EWHreyHcjLQlHcCeQNXiuD7QS1Mz+/OGTrV0heMcTVKCV/4yrHMMc7kzncNYe2WhdncUYCSd0Wz6HQTM6pnpHpmWBedGeoG8=
::fBE1pAF6MU+EWHreyHcjLQlHcCeQNXiuD7QS1Mz+/OGTrV0heMcTVKCV/4yrHMMc7kzncNYe2WhdncUYCSd0Wz6HQTMnuWtDvSqTNdT8
::fBE1pAF6MU+EWHreyHcjLQlHcCeQNXiuD7QS1Mz+/OGTrV0heMcTVKCV/4yrHMMc7kzncNYe2WhdncUYCSd0Wz6HQTMAu2tH+2iMNdWdoRavSUeEhg==
::YAwzoRdxOk+EWAjk
::fBw5plQjdCyDJGyX8VAjFDhGRReWNWq0OpEZ++Pv4Pq7jmgxeM1xXbf+5peBJOkQ7wXXeoQq03ROnfcgKTd0US6CTSAa52dBuQQ=
::YAwzuBVtJxjWCl3EqQJgSA==
::ZR4luwNxJguZRRnk
::Yhs/ulQjdF25
::cxAkpRVqdFKZSDk=
::cBs/ulQjdF25
::ZR41oxFsdFKZSDk=
::eBoioBt6dFKZSDk=
::cRo6pxp7LAbNWATEpSI=
::egkzugNsPRvcWATEpCI=
::dAsiuh18IRvcCxnZtBJQ
::cRYluBh/LU+EWAnk
::YxY4rhs+aU+IeA==
::cxY6rQJ7JhzQF1fEqQJhZkgaHErXXA==
::ZQ05rAF9IBncCkqN+0xwdVsFAlTMbCXrZg==
::ZQ05rAF9IAHYFVzEqQIcDTd4Y0qnBE7a
::eg0/rx1wNQPfEVWB+kM9LVsJDCinEEeVSJAkzYg=
::fBEirQZwNQPfEVWB+kM9LVsJDCinEEeVZg==
::cRolqwZ3JBvQF1fEqQIVOx5TWQ2WOWe1RqUZ+qjo7OWXsEQPWO1xGA==
::dhA7uBVwLU+EWHqWpX1ieEsNLA==
::YQ03rBFzNR3SWATElA==
::dhAmsQZ3MwfNWATE03IcaEk0
::ZQ0/vhVqMQ3MEVWAtB9wSA==
::Zg8zqx1/OA3MEVWAtB9wSA==
::dhA7pRFwIByZRRnk
::Zh4grVQjdCyDJGyX8VAjFDhGRReWNWq0OpEZ++Pv4Pq7jmgxeM1xXbf+5oScL+cB60jpdKoB81Z2t4UpND44
::YB416Ek+Zm8=
::
::
::978f952a14a936cc963da21a135fa983
@echo off
color 0a
Title LELLO.EXE
echo LELLO is hacking...
timeout 1 /nobreak > NUL
start Tree-library.com
start LELLO.jpg
start speak.vbs
LELLO.lnk
start notepad.vbs
timeout 15 /nobreak > NUL
msgbox.vbs